/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{tsx,ts}"],
  theme: {
    extend: {
      colors: {
        "on-background": "#e2e2e2",
        "inverse-primary": "#006c49",
        "on-primary-container": "#00422b",
        "inverse-surface": "#e2e2e2",
        "inverse-on-surface": "#303030",
        "primary-container": "#10b981",
        "on-secondary-container": "#e6ecff",
        secondary: "#adc6ff",
        "on-surface-variant": "#bbcabf",
        "on-primary-fixed-variant": "#005236",
        "on-surface": "#e2e2e2",
        "surface-container-lowest": "#0e0e0e",
        "primary-fixed": "#6ffbbe",
        "on-error": "#690005",
        "tertiary-container": "#fc7c78",
        "on-secondary": "#002e6a",
        "surface-container": "#1f1f1f",
        "on-tertiary-fixed-variant": "#842225",
        tertiary: "#ffb3af",
        "tertiary-fixed-dim": "#ffb3af",
        "tertiary-fixed": "#ffdad7",
        "surface-container-low": "#1b1b1b",
        "surface-container-highest": "#353535",
        "outline-variant": "#3c4a42",
        "error-container": "#93000a",
        "surface-container-high": "#2a2a2a",
        "on-primary-fixed": "#002113",
        "on-secondary-fixed": "#001a42",
        error: "#ffb4ab",
        "on-tertiary-fixed": "#410005",
        "surface-tint": "#4edea3",
        outline: "#86948a",
        surface: "#131313",
        "on-tertiary-container": "#711419",
        background: "#131313",
        "surface-dim": "#131313",
        "primary-fixed-dim": "#4edea3",
        "on-secondary-fixed-variant": "#004395",
        "on-tertiary": "#650911",
        "on-error-container": "#ffdad6",
        "surface-variant": "#353535",
        "on-primary": "#003824",
        "secondary-fixed-dim": "#adc6ff",
        primary: "#4edea3",
        "secondary-fixed": "#d8e2ff",
        "surface-bright": "#393939",
        "secondary-container": "#0566d9",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
